server:
  max-http-header-size : 80000 
  compression:
    enabled: true
    mime-types: application/json
spring:
  http:
    encoding:
      enable: false
  servlet:
    multipart:
        max-file-size: 2000MB
        max-request-size: 2001MB
  main:
    banner-mode: "off"
management:
    add-application-context-header: false