server:
  port: 9998
  servlet:
    contextPath: /dl/
es:
    port: 9200
    host: localhost
    path: 
ngt: http://localhost:8200/ngt/search
whiteshell: /data/dms/
#logging.level:
#  org.springframework: WARN